/**
 * Document.js — Mongoose model for processed documents (Phase 1)
 *
 * Stores the file provenance (original filename, storage path, MIME type,
 * size), the raw OCR text, semantic tags, and a nested `metadata` object
 * that captures the structured entities extracted by the Python AI
 * microservice (category, ID number, name, dates, auto-generated filename).
 *
 * Performance-critical indexes:
 *   • Compound index { userId: 1, 'metadata.documentCategory': 1 } → O(log n)
 *     dashboard queries scoped per user + category.
 *   • Text index { extractedText: 'text', tags: 'text' } → powers the
 *     "Smart Search" feature without full collection scans.
 */

const mongoose = require('mongoose');

const { Schema } = mongoose;

/** Enum of high-level document categories produced by the classifier. */
const DOCUMENT_CATEGORIES = ['ID Proof', 'Education', 'Finance', 'Insurance', 'Others'];

/**
 * Nested metadata document holding the structured entities extracted by the
 * AI pipeline. `_id` disabled — this is an embedded value object.
 */
const metadataSchema = new Schema(
  {
    documentCategory: {
      type: String,
      enum: {
        values: DOCUMENT_CATEGORIES,
        message: '{VALUE} is not a supported document category',
      },
      default: 'Others',
    },

    /** e.g. Aadhaar number, PAN number, passport number... */
    idNumber: {
      type: String,
      default: null,
      trim: true,
      maxlength: 64,
    },

    /** Entity name extracted from the document (card holder name). */
    name: {
      type: String,
      default: null,
      trim: true,
      maxlength: 128,
    },

    issueDate: {
      type: Date,
      default: null,
    },

    expiryDate: {
      type: Date,
      default: null,
    },

    /** Meaningful filename synthesized by the NLP module. */
    autoGeneratedFilename: {
      type: String,
      default: null,
      trim: true,
      maxlength: 255,
    },
  },
  { _id: false }
);

const documentSchema = new Schema(
  {
    /** Owning user — reference to the User model. */
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'A document must belong to a user'],
      index: true,
    },

    /** The name of the file as it arrived from the client. */
    originalFilename: {
      type: String,
      required: true,
      trim: true,
      maxlength: 255,
    },

    /** Absolute / container path (or object-storage key) where the raw file lives. */
    storagePath: {
      type: String,
      required: true,
      trim: true,
      maxlength: 1024,
    },

    mimeType: {
      type: String,
      required: true,
      trim: true,
      enum: {
        values: ['image/jpeg', 'image/png', 'application/pdf'],
        message: '{VALUE} is not an allowed upload MIME type',
      },
    },

    /** Size in bytes — enforced client-side and by Multer (15MB cap). */
    fileSize: {
      type: Number,
      required: true,
      min: [0, 'fileSize cannot be negative'],
    },

    /**
     * Background AI processing state.
     *
     * processing → AI service is working
     * completed  → document successfully processed
     * failed     → processing failed
     */
    processingStatus: {
      type: String,
      enum: ['processing', 'completed', 'failed'],
      default: 'processing',
      index: true,
    },

    /**
     * Stores the processing error when processingStatus === 'failed'.
     */
    processingError: {
      type: String,
      default: null,
      maxlength: 1000,
    },
    /** Specific document type classified by the Python AI service. */
    documentType: {
      type: String,
      default: 'Unknown',
      trim: true,
      maxlength: 64,
    },

    /** Structured entities extracted by the Python microservice. */
    metadata: {
      type: metadataSchema,
      default: () => ({}),
    },

    /** Raw OCR output produced by Tesseract (LSTM engine, eng+hin). */
    extractedText: {
      type: String,
      default: '',
      maxlength: 2 * 1024 * 1024,
    },

    /** Semantic tags / cluster labels computed by the embedding engine. */
    tags: {
      type: [String],
      default: [],
    },

    /**
     * Dense vector embedding of `extractedText` (all-MiniLM-L6-v2), used by
     * Phase 6 semantic grouping. Hidden from default projections to keep
     * API responses light; fetched explicitly when clustering is needed.
     */
    embedding: {
      type: [Number],
      default: undefined,
      select: false,
    },
  },
  {
    // Automatic `createdAt` / `updatedAt` timestamps
    timestamps: true,
    versionKey: false,
  }
);

/* ── Index strategy (Phase 1, § "Database Initialization") ──────────────── */

// 1. Compound index — user-scoped category browsing at O(log n).
documentSchema.index({
  userId: 1,
  'metadata.documentCategory': 1,
});

// 2. Text index — full-text Smart Search over extracted text + tags.
//    Weights bias matches in the extracted text over tag matches.
documentSchema.index(
  { extractedText: 'text', tags: 'text' },
  {
    name: 'doc_search_text',
    weights: {
      extractedText: 3,
      tags: 1,
    },
  }
);

// 3. Supporting index for the Expiry Alerts dashboard (30-day window scans).
documentSchema.index({
  userId: 1,
  'metadata.expiryDate': 1,
});

/**
 * Search a user's documents using the MongoDB text index.
 *
 * @param {string} userId - Owner ObjectId (string form).
 * @param {string} query - Raw search string.
 * @param {object} [opts] - { limit, skip } pagination options.
 * @returns {Promise<Array>} documents sorted by text-match relevance.
 */
/**
 * Smart search for a user's documents.
 *
 * Document-type searches use documentType/tags first.
 * Other searches can also match structured metadata and OCR text.
 * Matching is case-insensitive.
 */
documentSchema.statics.textSearch = function textSearch(
  userId,
  query,
  opts = {}
) {
  const { limit = 50, skip = 0 } = opts;

  const searchTerm = String(query || '').trim();

  if (!searchTerm) {
    return this.find({
      userId: mongoose.Types.ObjectId.createFromHexString(String(userId)),
    })
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean();
  }

  const userObjectId = mongoose.Types.ObjectId.createFromHexString(
    String(userId)
  );

  const DOCUMENT_TYPES = [
    'PAN',
    'Aadhaar',
    'Driving Licence',
    'Passport',
    'Voter ID',
    'Marksheet',
    'Study Plan',
    'Study Strategy',
    'Study Material',
    'Assignment',
    'Bank Statement',
    'Insurance',
    'Salary Slip',
    'Invoice',
    'Certificate',
    'Resume',
    'CV',
    'Form',
    'Report',
  ];

  const normalize = (value) =>
    String(value).toLowerCase().replace(/[^a-z0-9]/g, '');

  const normalizedSearch = normalize(searchTerm);

  /*
   * Check whether the user is searching for a document type.
   *
   * Examples:
   *   pan       -> PAN
   *   PAN       -> PAN
   *   resume    -> Resume
   *   drivinglicence -> Driving Licence
   *   aadhar    -> Aadhaar
   */
  const matchedType = DOCUMENT_TYPES.find((type) => {
    const normalizedType = normalize(type);

    if (normalizedType === normalizedSearch) {
      return true;
    }

    // Common Aadhaar spelling variation.
    if (
      type === 'Aadhaar' &&
      ['aadhar', 'aadhaar'].includes(normalizedSearch)
    ) {
      return true;
    }

    return false;
  });

  /*
   * If the query is a known document type, search only
   * documentType and tags.
   *
   * This prevents:
   *   PAN -> random OCR matches
   *   ID  -> "E-Mail ID" in a Resume
   */
  if (matchedType) {
    const typeRegex = new RegExp(
      `^${matchedType.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`,
      'i'
    );

    return this.find({
      userId: userObjectId,
      $or: [
        { documentType: typeRegex },
        { tags: typeRegex },
      ],
    })
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean();
  }

  /*
   * "ID" is too generic to search through OCR.
   * Treat it as an ID-document search instead.
   */
  if (normalizedSearch === 'id') {
    return this.find({
      userId: userObjectId,
      $or: [
        { documentType: /^Aadhaar$/i },
        { documentType: /^PAN$/i },
        { documentType: /^Driving Licence$/i },
        { documentType: /^Passport$/i },
        { documentType: /^Voter ID$/i },
        { tags: /^Aadhaar$/i },
        { tags: /^PAN$/i },
        { tags: /^Driving Licence$/i },
        { tags: /^Passport$/i },
        { tags: /^Voter ID$/i },
      ],
    })
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean();
  }

  /*
   * For names, ID numbers, filenames, categories and
   * normal text searches, use the broader search.
   */
  const escapedTerm = searchTerm.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(escapedTerm, 'i');

  return this.find({
    userId: userObjectId,
    $or: [
      { documentType: regex },
      { tags: regex },
      { 'metadata.documentCategory': regex },
      { 'metadata.name': regex },
      { 'metadata.idNumber': regex },
      { 'metadata.autoGeneratedFilename': regex },
      { originalFilename: regex },
      { extractedText: regex },
    ],
  })
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(limit)
    .lean();
};

module.exports = mongoose.model('Document', documentSchema);