import { useEffect, useState } from 'react';
import { useDocuments } from '../context/DocumentContext';
import { getDocumentFile } from '../api/client';

const CATEGORY_COLORS = {
  'ID Proof': 'bg-violet-100 text-violet-700',
  Finance: 'bg-emerald-100 text-emerald-700',
  Insurance: 'bg-sky-100 text-sky-700',
  Education: 'bg-amber-100 text-amber-700',
  Others: 'bg-slate-200 text-slate-600',
};

/** MIME-aware thumbnail placeholder. */
function FileThumb({ mimeType }) {
  const isPdf = mimeType === 'application/pdf';

  return (
    <div
      className={`flex h-24 w-20 shrink-0 items-center justify-center rounded-lg ${isPdf ? 'bg-rose-100' : 'bg-brand-50'
        }`}
    >
      <svg
        className={`h-10 w-10 ${isPdf ? 'text-rose-500' : 'text-brand-500'
          }`}
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={1.5}
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 1-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9z"
        />
      </svg>
    </div>
  );
}

function formatDate(value) {
  if (!value) return null;

  const d = new Date(value);

  if (Number.isNaN(d.getTime())) return null;

  return d.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

/**
 * DocumentCard
 *
 * Displays:
 * - document filename
 * - rename controls
 * - category
 * - tags
 * - extracted metadata
 * - preview button
 * - delete action
 */
export default function DocumentCard({ document: doc }) {
  const { remove, rename } = useDocuments();

  const [previewUrl, setPreviewUrl] = useState(null);
  const [previewType, setPreviewType] = useState(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState('');

  const meta = doc.metadata || {};
  const category = meta.documentCategory || 'Others';

  const currentFilename =
    meta.customFilename ||
    meta.autoGeneratedFilename ||
    doc.originalFilename;

  const [isRenaming, setIsRenaming] = useState(false);
  const [renameValue, setRenameValue] = useState(currentFilename);
  const [renameError, setRenameError] = useState('');
  const [renaming, setRenaming] = useState(false);

  const startRename = () => {
    setRenameValue(currentFilename);
    setRenameError('');
    setIsRenaming(true);
  };

  const cancelRename = () => {
    setRenameValue(currentFilename);
    setRenameError('');
    setIsRenaming(false);
  };

  const handleRename = async () => {
    const trimmedName = renameValue.trim();

    if (!trimmedName) {
      setRenameError('Filename cannot be empty.');
      return;
    }

    if (trimmedName.length > 200) {
      setRenameError('Filename must be 200 characters or fewer.');
      return;
    }

    setRenaming(true);
    setRenameError('');

    try {
      await rename(doc._id, trimmedName);
      setIsRenaming(false);
    } catch (err) {
      setRenameError(
        err.message || 'Could not rename document.'
      );
    } finally {
      setRenaming(false);
    }
  };

  const handlePreview = async () => {
    try {
      setPreviewLoading(true);
      setPreviewError('');

      const blob = await getDocumentFile(doc._id);

      const url = URL.createObjectURL(blob);

      setPreviewUrl(url);
      setPreviewType(blob.type);
    } catch (error) {
      console.error('Could not preview document:', error);

      setPreviewError(
        'Could not load the document preview.'
      );
    } finally {
      setPreviewLoading(false);
    }
  };

  const closePreview = () => {
    setPreviewUrl(null);
    setPreviewType(null);
    setPreviewError('');
  };

  /*
   * Clean up the object URL when the component is removed.
   */
  useEffect(() => {
    return () => {
      if (previewUrl) {
        URL.revokeObjectURL(previewUrl);
      }
    };
  }, [previewUrl]);

  /*
   * Close preview with the Escape key.
   */
  useEffect(() => {
    if (!previewUrl) return;

    const handleKeyDown = (event) => {
      if (event.key === 'Escape') {
        closePreview();
      }
    };

    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [previewUrl]);

  return (
    <>
      <article className="card group flex min-w-0 gap-3 p-4 transition-shadow hover:shadow-md sm:gap-4">
        <FileThumb mimeType={doc.mimeType} />

        <div className="min-w-0 flex-1">
          {isRenaming ? (
            <div className="space-y-2">
              <input
                type="text"
                value={renameValue}
                onChange={(e) => setRenameValue(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    handleRename();
                  }

                  if (e.key === 'Escape') {
                    cancelRename();
                  }
                }}
                autoFocus
                maxLength={200}
                className="w-full rounded-lg border border-brand-300 bg-white px-3 py-2 text-sm font-medium text-slate-800 outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100"
                aria-label="New filename"
              />

              {renameError && (
                <p className="text-xs text-rose-500">
                  {renameError}
                </p>
              )}

              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={handleRename}
                  disabled={renaming}
                  className="rounded-md bg-brand-600 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-brand-700 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  {renaming ? 'Saving...' : 'Save'}
                </button>

                <button
                  type="button"
                  onClick={cancelRename}
                  disabled={renaming}
                  className="rounded-md bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-600 transition hover:bg-slate-200 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <>
              {/* Filename + rename */}
              <div className="flex items-start gap-2">
                <h3
                  className="min-w-0 flex-1 break-words text-sm font-semibold leading-5 text-slate-800"
                  title={currentFilename}
                >
                  {currentFilename}
                </h3>

                <button
                  type="button"
                  onClick={startRename}
                  className="shrink-0 rounded-md p-1 text-slate-300 opacity-0 transition hover:bg-brand-50 hover:text-brand-600 focus:opacity-100 focus:outline-none group-hover:opacity-100"
                  aria-label="Rename document"
                  title="Rename document"
                >
                  <svg
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={1.8}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M16.862 4.487a2.25 2.25 0 1 1 3.182 3.182L7.5 20.213l-4.5 1.125 1.125-4.5L16.862 4.487Z"
                    />
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M15 6l3 3"
                    />
                  </svg>
                </button>
              </div>

              {/* Category + tags */}
              <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
                <span
                  className={`badge ${CATEGORY_COLORS[category] ||
                    CATEGORY_COLORS.Others
                    }`}
                >
                  {category}
                </span>

                {doc.tags?.slice(0, 2).map((tag) => (
                  <span
                    key={tag}
                    className="badge bg-slate-100 text-slate-500"
                  >
                    #{tag}
                  </span>
                ))}
              </div>

              {/* Document metadata */}
              <dl className="mt-2 space-y-1.5 text-xs text-slate-500">
                {meta.idNumber && (
                  <div className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3">
                    <dt className="font-medium text-slate-500">
                      ID No.
                    </dt>

                    <dd className="min-w-0 break-words font-mono font-medium text-slate-700">
                      {meta.idNumber}
                    </dd>
                  </div>
                )}

                {meta.name &&
                    ['PAN', 'Aadhaar', 'Marksheet', 'Driving Licence'].includes(
                      doc.documentType
                    ) && (
                      <div className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3">
                        <dt className="font-medium text-slate-500">
                          Name
                        </dt>

                        <dd className="min-w-0 break-words text-slate-700">
                          {meta.name}
                        </dd>
                      </div>
                    )
                }

                {meta.expiryDate && (
                  <div className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3">
                    <dt className="font-medium text-slate-500">
                      Expires
                    </dt>

                    <dd className="break-words font-medium text-amber-600">
                      {formatDate(meta.expiryDate)}
                    </dd>
                  </div>
                )}

                {meta.issueDate && (
                  <div className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3">
                    <dt className="font-medium text-slate-500">
                      Issued
                    </dt>

                    <dd className="break-words text-slate-700">
                      {formatDate(meta.issueDate)}
                    </dd>
                  </div>
                )}
              </dl>

              {/* Preview */}
              <div className="mt-3">
                <button
                  type="button"
                  onClick={handlePreview}
                  disabled={previewLoading}
                  className="inline-flex items-center gap-1.5 rounded-md bg-brand-50 px-3 py-1.5 text-xs font-medium text-brand-700 transition hover:bg-brand-100 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <svg
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={1.8}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M2.25 12s3.75-6.75 9.75-6.75S21.75 12 21.75 12 18 18.75 12 18.75 2.25 12 2.25 12Z"
                    />
                    <circle
                      cx="12"
                      cy="12"
                      r="2.5"
                    />
                  </svg>

                  {previewLoading ? 'Loading...' : 'Preview'}
                </button>

                {previewError && (
                  <p className="mt-1.5 text-xs text-rose-500">
                    {previewError}
                  </p>
                )}
              </div>
            </>
          )}
        </div>

        {/* Delete */}
        {!isRenaming && (
          <button
            type="button"
            onClick={() => remove(doc._id)}
            className="self-start shrink-0 rounded-md p-1 text-slate-300 opacity-0 transition-opacity hover:bg-rose-50 hover:text-rose-500 focus:opacity-100 group-hover:opacity-100"
            aria-label="Delete document"
            title="Delete document"
          >
            <svg
              className="h-4 w-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={1.8}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
              />
            </svg>
          </button>
        )}
      </article>

      {/* Preview modal */}
      {previewUrl && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4"
          role="dialog"
          aria-modal="true"
          aria-label={`Preview of ${currentFilename}`}
          onMouseDown={(event) => {
            if (event.target === event.currentTarget) {
              closePreview();
            }
          }}
        >
          <div className="relative flex max-h-[95vh] w-full max-w-5xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl">
            {/* Modal header */}
            <div className="flex shrink-0 items-center justify-between gap-4 border-b border-slate-200 px-4 py-3">
              <h2 className="min-w-0 flex-1 break-words text-sm font-semibold text-slate-800">
                {currentFilename}
              </h2>

              <button
                type="button"
                onClick={closePreview}
                className="shrink-0 rounded-lg p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
                aria-label="Close preview"
                title="Close preview"
              >
                <svg
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={1.8}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6 6l12 12M18 6L6 18"
                  />
                </svg>
              </button>
            </div>

            {/* Preview content */}
            <div className="min-h-0 flex-1 overflow-auto bg-slate-100 p-3 sm:p-5">
              {previewType === 'application/pdf' ? (
                <iframe
                  src={previewUrl}
                  title={`Preview of ${currentFilename}`}
                  className="h-[75vh] w-full rounded-lg border border-slate-200 bg-white"
                />
              ) : previewType?.startsWith('image/') ? (
                <div className="flex min-h-[60vh] items-center justify-center">
                  <img
                    src={previewUrl}
                    alt={currentFilename}
                    className="max-h-[75vh] max-w-full rounded-lg object-contain shadow-sm"
                  />
                </div>
              ) : (
                <div className="flex min-h-[60vh] items-center justify-center text-sm text-slate-500">
                  Preview is not available for this file type.
                </div>
              )}
            </div>

            {/* Modal footer */}
            <div className="flex shrink-0 items-center justify-end border-t border-slate-200 bg-white px-4 py-3">
              <button
                type="button"
                onClick={closePreview}
                className="rounded-lg bg-slate-100 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-200"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}