import { useDocuments } from '../context/DocumentContext';

const CATEGORY_COLORS = {
  'ID Proof': 'bg-violet-100 text-violet-700',
  Finance: 'bg-emerald-100 text-emerald-700',
  Insurance: 'bg-sky-100 text-sky-700',
  Education: 'bg-amber-100 text-amber-700',
  Others: 'bg-slate-200 text-slate-600',
};

/** MIME-aware thumbnail placeholder. */
function FileThumb({ mimeType }) {
  const isPdf = mimeType === 'application/pdf';
  return (
    <div className={`flex h-24 w-20 shrink-0 items-center justify-center rounded-lg ${isPdf ? 'bg-rose-100' : 'bg-brand-50'}`}>
      <svg className={`h-10 w-10 ${isPdf ? 'text-rose-500' : 'text-brand-500'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9z"
        />
      </svg>
    </div>
  );
}

function formatDate(value) {
  if (!value) return null;
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

/**
 * DocumentCard — single library tile (Phase 7): auto-generated filename,
 * extracted ID number, category badge, tags and expiry indicator.
 */
export default function DocumentCard({ document: doc }) {
  const { remove } = useDocuments();
  const meta = doc.metadata || {};
  const category = meta.documentCategory || 'Others';

  return (
    <article className="card group flex gap-4 p-4 transition-shadow hover:shadow-md">
      <FileThumb mimeType={doc.mimeType} />

      <div className="min-w-0 flex-1">
        <h3
          className="truncate text-sm font-semibold text-slate-800"
          title={meta.autoGeneratedFilename || doc.originalFilename}
        >
          {meta.autoGeneratedFilename || doc.originalFilename}
        </h3>

        <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
          <span className={`badge ${CATEGORY_COLORS[category] || CATEGORY_COLORS.Others}`}>
            {category}
          </span>
          {doc.tags?.slice(0, 2).map((tag) => (
            <span key={tag} className="badge bg-slate-100 text-slate-500">
              #{tag}
            </span>
          ))}
        </div>

        <dl className="mt-2 space-y-0.5 text-xs text-slate-500">
          {meta.idNumber && (
            <div className="flex justify-between gap-2">
              <dt className="shrink-0">ID No.</dt>
              <dd className="truncate font-mono font-medium text-slate-700">{meta.idNumber}</dd>
            </div>
          )}
          {meta.name && (
            <div className="flex justify-between gap-2">
              <dt className="shrink-0">Name</dt>
              <dd className="truncate">{meta.name}</dd>
            </div>
          )}
          {meta.expiryDate && (
            <div className="flex justify-between gap-2">
              <dt className="shrink-0">Expires</dt>
              <dd className="truncate font-medium text-amber-600">{formatDate(meta.expiryDate)}</dd>
            </div>
          )}
          {meta.issueDate && (
            <div className="flex justify-between gap-2">
              <dt className="shrink-0">Issued</dt>
              <dd className="truncate">{formatDate(meta.issueDate)}</dd>
            </div>
          )}
        </dl>
      </div>

      <button
        onClick={() => remove(doc._id)}
        className="self-start rounded-md p-1 text-slate-300 opacity-0 transition-opacity hover:bg-rose-50 hover:text-rose-500 focus:opacity-100 group-hover:opacity-100"
        aria-label="Delete document"
        title="Delete document"
      >
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
        </svg>
      </button>
    </article>
  );
}
