import { useMemo } from 'react';
import { useDocuments } from '../context/DocumentContext';

const WARNING_ICON = (
  <svg
    className="h-4 w-4 shrink-0 text-amber-500"
    fill="currentColor"
    viewBox="0 0 24 24"
  >
    <path
      fillRule="evenodd"
      d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5z"
      clipRule="evenodd"
    />
  </svg>
);

function daysUntil(date) {
  const target = new Date(date);
  const now = new Date();

  return Math.ceil(
    (target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
  );
}

/**
 * ExpiryAlerts — sidebar widget.
 *
 * Shows documents whose expiry date falls within the next 30 days.
 * Documents that have already expired are highlighted separately.
 */
export default function ExpiryAlerts() {
  const { expiring } = useDocuments();

  const sorted = useMemo(
    () =>
      [...expiring].sort(
        (a, b) =>
          new Date(a.metadata?.expiryDate) -
          new Date(b.metadata?.expiryDate)
      ),
    [expiring]
  );

  return (
    <aside className="rounded-2xl border border-violet-100 bg-white p-5 shadow-sm">
      {/* Header */}
      <div className="flex items-center gap-3">
        <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-100">
          {WARNING_ICON}
        </span>

        <div className="min-w-0">
          <h2 className="text-sm font-bold text-slate-800">
            Expiry Alerts
          </h2>
          <p className="text-[11px] text-slate-400">
            Next 30 days
          </p>
        </div>

        <span className="ml-auto flex h-7 min-w-7 items-center justify-center rounded-full bg-violet-100 px-2 text-xs font-bold text-violet-700">
          {sorted.length}
        </span>
      </div>

      {/* Divider */}
      <div className="my-4 h-px bg-violet-50" />

      {sorted.length === 0 ? (
        <div className="rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-3">
          <p className="text-xs font-semibold text-emerald-700">
            ✓ All clear
          </p>
          <p className="mt-0.5 text-[11px] text-emerald-600">
            No documents expire in the next 30 days.
          </p>
        </div>
      ) : (
        <ul className="space-y-3">
          {sorted.map((doc) => {
            const days = daysUntil(doc.metadata?.expiryDate);
            const expired = days < 0;
            const urgent = days <= 7;

            return (
              <li
                key={doc._id}
                className={`rounded-xl border p-3 transition ${
                  expired
                    ? 'border-rose-200 bg-rose-50'
                    : urgent
                      ? 'border-amber-200 bg-amber-50'
                      : 'border-violet-100 bg-violet-50/40'
                }`}
              >
                <div className="flex items-start gap-2.5">
                  <span
                    className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${
                      expired
                        ? 'bg-rose-100'
                        : urgent
                          ? 'bg-amber-100'
                          : 'bg-violet-100'
                    }`}
                  >
                    {WARNING_ICON}
                  </span>

                  <div className="min-w-0 flex-1">
                    <p className="truncate text-xs font-bold text-slate-700">
                      {doc.metadata?.autoGeneratedFilename ||
                        doc.originalFilename}
                    </p>

                    <p className="mt-1 text-[11px] text-slate-500">
                      Expires{' '}
                      {new Date(
                        doc.metadata?.expiryDate
                      ).toLocaleDateString()}
                    </p>

                    <span
                      className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${
                        expired
                          ? 'bg-rose-100 text-rose-700'
                          : urgent
                            ? 'bg-amber-100 text-amber-700'
                            : 'bg-violet-100 text-violet-700'
                      }`}
                    >
                      {expired
                        ? 'EXPIRED'
                        : `${days} day${days === 1 ? '' : 's'} left`}
                    </span>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </aside>
  );
}