import { useMemo } from 'react';
import { useDocuments } from '../context/DocumentContext';

const WARNING_ICON = (
  <svg className="h-4 w-4 shrink-0 text-amber-500" fill="currentColor" viewBox="0 0 24 24">
    <path
      fillRule="evenodd"
      d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5z"
      clipRule="evenodd"
    />
  </svg>
);

function daysUntil(date) {
  const target = new Date(date);
  const now = new Date();
  return Math.ceil((target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

/**
 * ExpiryAlerts — sidebar widget (Phase 7).
 *
 * Renders documents whose `metadata.expiryDate` falls within the next 30
 * days (server-enforced window) with high-visibility warning iconography and
 * a countdown label. Documents already expired are flagged as such.
 */
export default function ExpiryAlerts() {
  const { expiring } = useDocuments();

  const sorted = useMemo(
    () => [...expiring].sort((a, b) => new Date(a.metadata?.expiryDate) - new Date(b.metadata?.expiryDate)),
    [expiring]
  );

  return (
    <aside className="card p-5">
      <div className="flex items-center gap-2">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-100">
          {WARNING_ICON}
        </span>
        <div>
          <h2 className="text-sm font-bold text-slate-800">Expiry Alerts</h2>
          <p className="text-[11px] text-slate-400">Next 30 days</p>
        </div>
        <span className="badge ml-auto bg-amber-100 text-amber-700">
          {sorted.length}
        </span>
      </div>

      {sorted.length === 0 ? (
        <p className="mt-4 rounded-lg bg-emerald-50 px-3 py-2.5 text-xs font-medium text-emerald-700">
          ✓ No documents expiring in the next 30 days.
        </p>
      ) : (
        <ul className="mt-4 space-y-2.5">
          {sorted.map((doc) => {
            const days = daysUntil(doc.metadata?.expiryDate);
            const expired = days < 0;
            const urgent = days <= 7;
            return (
              <li
                key={doc._id}
                className={`flex items-start gap-2.5 rounded-lg border p-2.5 ${
                  expired
                    ? 'border-rose-200 bg-rose-50'
                    : urgent
                      ? 'border-amber-200 bg-amber-50'
                      : 'border-slate-200 bg-slate-50'
                }`}
              >
                {WARNING_ICON}
                <div className="min-w-0">
                  <p className="truncate text-xs font-semibold text-slate-700">
                    {doc.metadata?.autoGeneratedFilename || doc.originalFilename}
                  </p>
                  <p className="mt-0.5 text-[11px] text-slate-500">
                    Expires {new Date(doc.metadata?.expiryDate).toLocaleDateString()}
                  </p>
                  <span
                    className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[10px] font-bold ${
                      expired ? 'bg-rose-100 text-rose-700' : urgent ? 'bg-amber-100 text-amber-700' : 'bg-slate-200 text-slate-600'
                    }`}
                  >
                    {expired ? 'EXPIRED' : `${days} day${days === 1 ? '' : 's'} left`}
                  </span>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </aside>
  );
}
