import { useMemo } from 'react';
import { useDocuments } from '../context/DocumentContext';

const WARNING_ICON = (
  <svg
    className="h-4 w-4 shrink-0 text-amber-500"
    fill="currentColor"
    viewBox="0 0 24 24"
  >
    <path
      fillRule="evenodd"
      d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5z"
      clipRule="evenodd"
    />
  </svg>
);

function daysUntil(date) {
  const target = new Date(date);
  const now = new Date();

  return Math.ceil(
    (target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
  );
}

/**
 * ExpiryAlerts — sidebar widget.
 *
 * Shows documents whose expiry date falls within the next 30 days.
 * Documents that have already expired are highlighted separately.
 */
export default function ExpiryAlerts() {
  const { expiring } = useDocuments();

  const sorted = useMemo(
    () =>
      [...expiring].sort(
        (a, b) =>
          new Date(a.metadata?.expiryDate) -
          new Date(b.metadata?.expiryDate)
      ),
    [expiring]
  );

  return (
    <section className="surface overflow-hidden" aria-labelledby="expiry-heading">
      <div className="border-b border-slate-200 px-4 py-4 sm:px-5">
        <div className="flex items-center gap-3">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-amber-50">
            {WARNING_ICON}
          </span>
          <div className="min-w-0">
            <h2 id="expiry-heading" className="text-sm font-bold text-slate-900">Expiry alerts</h2>
            <p className="text-xs text-slate-500">Next 30 days</p>
          </div>
          <span className="ml-auto flex h-7 min-w-7 items-center justify-center rounded-full bg-amber-50 px-2 text-xs font-bold tabular-nums text-amber-800" aria-label={`${sorted.length} documents expiring soon`}>
            {sorted.length}
          </span>
        </div>
      </div>

      {sorted.length === 0 ? (
        <div className="motion-enter flex items-start gap-3 px-4 py-5 sm:px-5">
          <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-sm font-bold text-emerald-700" aria-hidden="true">✓</span>
          <div>
            <p className="text-sm font-semibold text-slate-800">You’re all caught up</p>
            <p className="mt-1 text-xs leading-5 text-slate-500">No documents expire in the next 30 days.</p>
          </div>
        </div>
      ) : (
        <ul className="motion-stagger divide-y divide-slate-100">
          {sorted.map((doc) => {
            const days = daysUntil(doc.metadata?.expiryDate);
            const expired = days < 0;
            const urgent = days <= 7;

            return (
              <li
                key={doc._id}
                className={`px-4 py-3.5 transition-colors sm:px-5 ${
                  expired
                    ? 'bg-rose-50/60'
                    : urgent
                      ? 'bg-amber-50/60'
                      : 'bg-white hover:bg-slate-50'
                }`}
              >
                <div className="flex items-start gap-2.5">
                  <span
                    className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-md ${
                      expired
                        ? 'bg-rose-100'
                        : urgent
                          ? 'bg-amber-100'
                          : 'bg-slate-100'
                    }`}
                  >
                    {WARNING_ICON}
                  </span>

                  <div className="min-w-0 flex-1">
                    <p className="break-words text-sm font-semibold leading-5 text-slate-800">
                      {doc.metadata?.autoGeneratedFilename ||
                        doc.originalFilename}
                    </p>

                    <p className="mt-1 text-xs text-slate-500">
                      Expires{' '}
                      {new Date(
                        doc.metadata?.expiryDate
                      ).toLocaleDateString()}
                    </p>

                    <span
                      className={`mt-2 inline-flex rounded-md px-2 py-1 text-[11px] font-semibold ${
                        expired
                          ? 'bg-rose-100 text-rose-700'
                          : urgent
                            ? 'bg-amber-100 text-amber-700'
                            : 'bg-slate-100 text-slate-700'
                      }`}
                    >
                      {expired
                        ? 'EXPIRED'
                        : `${days} day${days === 1 ? '' : 's'} left`}
                    </span>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </section>
  );
}