import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';

import {
  deleteDocument as apiDelete,
  fetchDocuments,
  fetchExpiring,
  getDocument,
  uploadDocument as apiUpload,
} from '../api/client';
import { showNotification } from '../services/notifications.js';
const DocumentContext = createContext(null);

const sleep = (ms) =>
  new Promise((resolve) => setTimeout(resolve, ms));

export function DocumentProvider({ children }) {
  const [documents, setDocuments] = useState([]);
  const [expiring, setExpiring] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [searching, setSearching] = useState(false);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(null);

  const [uploadState, setUploadState] = useState({
    status: 'idle',
    progress: 0,
    fileName: null,
    error: null,
  });

  const refresh = useCallback(async () => {
    try {
      setLoading(true);
      setLoadError(null);

      const [docs, exp] = await Promise.all([
        fetchDocuments(),
        fetchExpiring(),
      ]);

      setDocuments(docs);
      setExpiring(exp);

      exp.forEach((doc) => {
        const expiryDate = doc.metadata?.expiryDate;

        if (!expiryDate) return;

        const daysLeft = Math.ceil(
          (new Date(expiryDate).getTime() - Date.now()) /
          (1000 * 60 * 60 * 24)
        );

        const notificationKey = `expiry-notified-${doc._id}-${expiryDate}`;

        if (localStorage.getItem(notificationKey)) {
          return;
        }

        showNotification('Document expiry reminder', {
          body: `${doc.metadata?.autoGeneratedFilename || doc.originalFilename || 'Your document'} expires in ${daysLeft} days.`,
        });

        localStorage.setItem(notificationKey, 'true');
      });
    } catch (err) {
      setLoadError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  /**
   * Smart Search
   */
  const applySearch = useCallback(
    async (query) => {
      const trimmed = (query || '').trim();

      setSearchQuery(trimmed);

      if (!trimmed) {
        await refresh();
        return;
      }

      setSearching(true);

      try {
        const docs = await fetchDocuments({ search: trimmed });
        setDocuments(docs);
        setLoadError(null);
      } catch (err) {
        setLoadError(err.message);
      } finally {
        setSearching(false);
      }
    },
    [refresh]
  );

  /**
   * Poll one document until processing finishes.
   *
   * There is intentionally NO timeout here.
   * AI processing can take longer depending on OCR,
   * embeddings and document size.
   */
  const monitorDocument = useCallback(async (uploadedDoc) => {
    while (true) {
      await sleep(2000);

      try {
        const currentDoc = await getDocument(uploadedDoc._id);

        // Automatically update the document in the library.
        setDocuments((docs) => {
          const exists = docs.some(
            (doc) =>
              String(doc._id) === String(currentDoc._id)
          );

          if (exists) {
            return docs.map((doc) =>
              String(doc._id) === String(currentDoc._id)
                ? currentDoc
                : doc
            );
          }

          return [currentDoc, ...docs];
        });

        if (currentDoc.processingStatus === 'completed') {
          showNotification('Document processed successfully', {
            body: `${currentDoc.metadata?.autoGeneratedFilename || currentDoc.originalFilename || 'Your document'} is ready in your library.`,
          });
          try {
            const updatedExpiring = await fetchExpiring();
            setExpiring(updatedExpiring);
          } catch (err) {
            console.warn(
              '[frontend] Could not refresh expiry alerts:',
              err.message
            );
          }

          return {
            status: 'completed',
            document: currentDoc,
          };
        }

        if (currentDoc.processingStatus === 'failed') {
          showNotification('Document processing failed', {
            body: `${currentDoc.originalFilename || 'Your document'} could not be processed.`,
          });
          return {
            status: 'failed',
            document: currentDoc,
          };
        }
      } catch (err) {
        // A temporary frontend request failure should NOT
        // mark the document as failed.
        console.warn(
          `[frontend] Could not check document ${uploadedDoc._id}:`,
          err.message
        );
      }
    }
  }, []);

  /**
   * Upload multiple documents.
   *
   * Upload completion and AI processing completion
   * are treated as two separate things.
   */
  const upload = useCallback(
    async (files) => {
      const fileList = Array.isArray(files) ? files : [files];

      if (fileList.length === 0) {
        return [];
      }

      const fileNames = fileList
        .map((file) => file.name)
        .join(', ');

      setUploadState({
        status: 'uploading',
        progress: 0,
        fileName: fileNames,
        error: null,
      });

      try {
        /**
         * Send all selected files to the backend.
         */
        const uploadedDocs = await apiUpload(
          fileList,
          (pct) => {
            setUploadState((state) =>
              state.status === 'uploading'
                ? {
                  ...state,
                  progress: pct,
                }
                : state
            );
          }
        );

        if (
          !Array.isArray(uploadedDocs) ||
          uploadedDocs.length === 0
        ) {
          throw new Error(
            'No documents were created by the server.'
          );
        }

        /**
         * Immediately add the newly uploaded documents
         * to the library.
         */
        setDocuments((docs) => {
          const newIds = new Set(
            uploadedDocs.map((doc) => String(doc._id))
          );

          return [
            ...uploadedDocs,
            ...docs.filter(
              (doc) => !newIds.has(String(doc._id))
            ),
          ];
        });

        /**
         * Upload itself is now successful.
         *
         * AI processing continues independently.
         */
        setUploadState({
          status: 'processing',
          progress: 100,
          fileName:
            fileList.length === 1
              ? fileList[0].name
              : `${fileList.length} documents uploaded`,
          error: null,
        });

        /**
         * Start independent background monitoring.
         *
         * We intentionally DO NOT await Promise.all here.
         */
        let completedCount = 0;
        let hasFailed = false;

        uploadedDocs.forEach((uploadedDoc) => {
          void monitorDocument(uploadedDoc).then((result) => {
            if (result.status === 'completed') {
              setDocuments((docs) =>
                docs.map((doc) =>
                  String(doc._id) ===
                    String(result.document._id)
                    ? result.document
                    : doc
                )
              );
            }

            if (result.status === 'failed') {
              hasFailed = true;

              setDocuments((docs) =>
                docs.map((doc) =>
                  String(doc._id) ===
                    String(result.document._id)
                    ? result.document
                    : doc
                )
              );
            }

            completedCount += 1;

            // All documents have finished processing.
            if (completedCount === uploadedDocs.length) {
              setUploadState((state) => ({
                ...state,
                status: hasFailed ? 'error' : 'success',
                progress: 100,
                error: hasFailed
                  ? 'One or more documents failed during AI processing.'
                  : null,
              }));
            }
          });
        });

        /**
         * Return immediately after the server has accepted
         * the files.
         */
        return uploadedDocs;
      } catch (err) {
        setUploadState({
          status: 'error',
          progress: 0,
          fileName: fileNames,
          error: err.message,
        });

        throw err;
      }
    },
    [monitorDocument]
  );

  /**
   * Delete document.
   */
  const remove = useCallback(async (id) => {
    await apiDelete(id);

    setDocuments((docs) =>
      docs.filter(
        (doc) => String(doc._id) !== String(id)
      )
    );

    setExpiring((docs) =>
      docs.filter(
        (doc) => String(doc._id) !== String(id)
      )
    );
  }, []);

  const value = useMemo(
    () => ({
      documents,
      expiring,
      searchQuery,
      searching,
      applySearch,
      loading,
      loadError,
      uploadState,
      upload,
      remove,
      refresh,
    }),
    [
      documents,
      expiring,
      searchQuery,
      searching,
      applySearch,
      loading,
      loadError,
      uploadState,
      upload,
      remove,
      refresh,
    ]
  );

  return (
    <DocumentContext.Provider value={value}>
      {children}
    </DocumentContext.Provider>
  );
}

export function useDocuments() {
  const ctx = useContext(DocumentContext);

  if (!ctx) {
    throw new Error(
      'useDocuments must be used inside <DocumentProvider>'
    );
  }

  return ctx;
}