/**
 * aiService.js — HTTP client for the Python FastAPI microservice (Phase 2)
 *
 * Constructs a `multipart/form-data` POST request containing the temporarily
 * saved file and dispatches it to the AI service. Fully decoupled from the
 * Express event loop: axios performs the I/O asynchronously and the caller
 * awaits the structured JSON result.
 *
 * Optional `existingEmbeddings` payload lets the AI service compute semantic
 * similarity against previously ingested documents (Phase 6 clustering).
 */

const fs = require('fs');
const axios = require('axios');
const FormData = require('form-data');

const AI_SERVICE_URL = process.env.AI_SERVICE_URL || 'http://localhost:8000';
const AI_TIMEOUT_MS = Number(process.env.AI_TIMEOUT_MS || 120000);

/**
 * Dispatch a temporarily-saved upload to the AI service.
 *
 * @param {Express.Multer.File} file - Multer file descriptor ({ path, originalname, mimetype, size }).
 * @param {object} [options]
 * @param {Array<{embedding: number[], tag: string}>} [options.existingEmbeddings]
 *        Existing document vectors for semantic cluster-join.
 * @returns {Promise<object>} The AI service's structured JSON response:
 *   { originalFilename, mimeType, fileSize, extractedText, cleanedTextArray,
 *     documentType, metadata: { documentCategory, idNumber, name, issueDate,
 *     expiryDate, autoGeneratedFilename }, tags, embedding, clusterTag,
 *     similarityScore }
 */
async function processDocument(file, options = {}) {
  const form = new FormData();

  // Stream the file body instead of buffering it into memory.
  form.append('file', fs.createReadStream(file.path), {
    filename: file.originalname,
    contentType: file.mimetype,
  });

  // Phase 6: forward existing embeddings so the AI service can compute
  // cosine similarity and join the new document to a semantic cluster.
  if (options.existingEmbeddings && options.existingEmbeddings.length > 0) {
    form.append('existing_embeddings', JSON.stringify(options.existingEmbeddings));
  }

  const response = await axios.post(`${AI_SERVICE_URL}/process-document`, form, {
    headers: form.getHeaders(),
    timeout: AI_TIMEOUT_MS,
    // Long OCR + embedding jobs can exceed the default 10MB response cap.
    maxContentLength: 64 * 1024 * 1024,
    maxBodyLength: 64 * 1024 * 1024,
    // Validate the payload contract early so controllers can trust the shape.
    validateStatus: (status) => status >= 200 && status < 300,
  });

  return response.data;
}

module.exports = { processDocument, AI_SERVICE_URL, AI_TIMEOUT_MS };
