/**
 * documentController.js — Orchestration logic (Phase 2)
 *
 * POST /api/documents/upload  → save the uploaded file + create a processing
 *                               job, then process the AI task in the background.
 * GET  /api/documents         → list / smart-search the user's documents.
 * GET  /api/documents/expiring→ documents expiring within 30 days (dashboard).
 * GET  /api/documents/:id     → single document.
 * DELETE /api/documents/:id   → remove document (+ its storage artifact).
 */

const fs = require('fs');
const path = require('path');
const Document = require('../models/Document');
const aiService = require('../services/aiService');
const { uploadDir } = require('../middleware/multerConfig');

const EXPIRY_WINDOW_DAYS = 30;

/** Best-effort cleanup of a temporary upload artifact. */
function safeUnlink(filePath) {
  return fs.promises.unlink(filePath).catch((err) => {
    console.warn(
      `[gateway] Could not remove temp file ${filePath}: ${err.message}`
    );
  });
}

/**
 * Process a document in the background.
 *
 * This function intentionally runs outside the HTTP response flow.
 * The upload endpoint can respond immediately while this work continues.
 */
async function processDocumentInBackground({
  documentId,
  file,
  userId,
  existingEmbeddings,
}) {
  try {
    console.log(
      `[gateway] Background processing started for document ${documentId}`
    );

    // ── Dispatch to the Python AI microservice ─────────────────────────────
    const aiResult = await aiService.processDocument(file, {
      existingEmbeddings,
    });

    // ── Map the AI response into the Document schema ───────────────────────
    const metadata = aiResult.metadata || {};

    await Document.findOneAndUpdate(
      {
        _id: documentId,
        userId,
      },
      {
        $set: {
          extractedText: aiResult.extractedText || '',
          tags: Array.isArray(aiResult.tags) ? aiResult.tags : [],
          embedding: aiResult.embedding || undefined,

          metadata: {
            documentCategory: metadata.documentCategory || 'Others',
            idNumber: metadata.idNumber ?? null,
            name: metadata.name ?? null,
            issueDate: metadata.issueDate || null,
            expiryDate: metadata.expiryDate || null,
            autoGeneratedFilename:
              metadata.autoGeneratedFilename || file.originalname,
          },

          processingStatus: 'completed',
          processingError: null,
        },
      }
    );

    console.log(
      `[gateway] Background processing completed for document ${documentId}`
    );
  } catch (err) {
    console.error(
      `[gateway] Background processing failed for document ${documentId}:`,
      err.message
    );

    try {
      await Document.findOneAndUpdate(
        {
          _id: documentId,
          userId,
        },
        {
          $set: {
            processingStatus: 'failed',
            processingError: err.message || 'Document processing failed',
          },
        }
      );
    } catch (updateError) {
      console.error(
        `[gateway] Could not update failed status for document ${documentId}:`,
        updateError.message
      );
    }
  }
}

/**
 * POST /api/documents/upload
 * Requires: Bearer token + multipart field `file`.
 *
 * The endpoint now returns quickly after creating the document record.
 * AI processing continues in the background.
 */
/**
 * POST /api/documents/upload
 * Requires: Bearer token + multipart field `file`.
 *
 * Supports multiple files (up to 10).
 * Each document gets its own MongoDB record and background
 * processing job.
 */
async function uploadDocument(req, res, next) {
  try {
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({
        error: 'No files uploaded. Expected multipart field "file".',
      });
    }

    const files = req.files;

    // ── Pull existing embeddings for semantic clustering ────────────────
    let existingEmbeddings = [];

    try {
      existingEmbeddings = await Document.find({
        userId: req.userId,
        embedding: { $exists: true, $ne: [] },
      })
        .select('+embedding _id tags')
        .lean()
        .then((docs) =>
          docs.map((d) => ({
            _id: String(d._id),
            embedding: d.embedding,
            tag: d.tags?.[0] || null,
          }))
        )
        .catch(() => []);
    } catch {
      /* clustering is best-effort; never block ingestion */
    }

    // ── Create + start processing for each file independently ──────────
    const createdDocuments = [];

    for (const file of files) {
      try {
        // Create initial MongoDB record immediately.
        const doc = await Document.create({
          userId: req.userId,
          originalFilename: file.originalname,
          storagePath: file.path,
          mimeType: file.mimetype,
          fileSize: file.size,

          processingStatus: 'processing',
          processingError: null,

          extractedText: '',
          tags: [],
          embedding: undefined,

          metadata: {
            documentCategory: 'Others',
            idNumber: null,
            name: null,
            issueDate: null,
            expiryDate: null,
            autoGeneratedFilename: file.originalname,
          },
        });

        // Start this document's AI processing independently.
        void processDocumentInBackground({
          documentId: doc._id,
          file,
          userId: req.userId,
          existingEmbeddings,
        });

        createdDocuments.push(
          await doc.populate('userId', 'username email')
        );
      } catch (fileError) {
        // If this particular file fails during DB creation,
        // clean up only that file and continue with the others.
        await safeUnlink(file.path);

        console.error(
          `[gateway] Could not create document for ${file.originalname}:`,
          fileError.message
        );
      }
    }

    // If every file failed during document creation.
    if (createdDocuments.length === 0) {
      return res.status(500).json({
        error: 'Could not create any document records.',
      });
    }

    // ── Respond immediately ────────────────────────────────────────────
    return res.status(202).json({
      success: true,
      message: `${createdDocuments.length} document(s) uploaded successfully and processing started.`,
      documents: createdDocuments,
    });
  } catch (err) {
    // Cleanup all uploaded files if an unexpected error occurs
    // before normal processing can be started.
    if (Array.isArray(req.files)) {
      await Promise.all(
        req.files.map((file) => safeUnlink(file.path))
      );
    }

    return next(err);
  }
}

/**
 * GET /api/documents?search=<query>&category=<cat>&limit=&skip=
 * Uses the MongoDB text index when `search` is present, otherwise a
 * userId + category compound-index scan.
 */
async function listDocuments(req, res, next) {
  try {
    const { search, category, limit = 50, skip = 0 } = req.query;

    const numericLimit = Math.min(Number(limit) || 50, 100);
    const numericSkip = Math.max(Number(skip) || 0, 0);

    let documents;

    if (search && String(search).trim()) {
      // Full-text search powered by the { extractedText, tags } text index.
      documents = await Document.textSearch(
        req.userId,
        String(search).trim(),
        {
          limit: numericLimit,
          skip: numericSkip,
        }
      );
    } else {
      const filter = {
        userId: req.userId,
      };

      if (category) {
        filter['metadata.documentCategory'] = category;
      }

      documents = await Document.find(filter)
        .sort({ createdAt: -1 })
        .skip(numericSkip)
        .limit(numericLimit)
        .lean();
    }

    return res.json({
      success: true,
      count: documents.length,
      documents,
    });
  } catch (err) {
    return next(err);
  }
}

/**
 * GET /api/documents/expiring
 *
 * Documents whose `metadata.expiryDate` falls inside the next 30 days.
 */
async function listExpiring(req, res, next) {
  try {
    const now = new Date();

    const horizon = new Date(
      now.getTime() + EXPIRY_WINDOW_DAYS * 24 * 60 * 60 * 1000
    );

    const documents = await Document.find({
      userId: req.userId,
      'metadata.expiryDate': {
        $gte: now,
        $lte: horizon,
      },
    })
      .sort({ 'metadata.expiryDate': 1 })
      .lean();

    return res.json({
      success: true,
      windowDays: EXPIRY_WINDOW_DAYS,
      count: documents.length,
      documents,
    });
  } catch (err) {
    return next(err);
  }
}

/**
 * GET /api/documents/:id
 */
async function getDocument(req, res, next) {
  try {
    const doc = await Document.findOne({
      _id: req.params.id,
      userId: req.userId,
    }).lean();

    if (!doc) {
      return res.status(404).json({
        error: 'Document not found',
      });
    }

    return res.json({
      success: true,
      document: doc,
    });
  } catch (err) {
    return next(err);
  }
}

/**
 * DELETE /api/documents/:id
 * Removes the DB record and its stored artifact.
 */
async function deleteDocument(req, res, next) {
  try {
    const doc = await Document.findOneAndDelete({
      _id: req.params.id,
      userId: req.userId,
    });

    if (!doc) {
      return res.status(404).json({
        error: 'Document not found',
      });
    }

    // Artifact may live outside uploadDir (object storage) — attempt only
    // when the resolved path stays inside the configured cache directory.
    const resolved = path.resolve(doc.storagePath);

    if (resolved.startsWith(path.resolve(uploadDir))) {
      await safeUnlink(resolved);
    }

    return res.json({
      success: true,
      deletedId: doc._id,
    });
  } catch (err) {
    return next(err);
  }
}

module.exports = {
  uploadDocument,
  listDocuments,
  listExpiring,
  getDocument,
  deleteDocument,
  EXPIRY_WINDOW_DAYS,
};