/**
 * documentController.js — Orchestration logic (Phase 2)
 *
 * POST /api/documents/upload  → dispatch file to the Python AI service,
 *                               persist the enriched metadata, respond.
 * GET  /api/documents         → list / smart-search the user's documents.
 * GET  /api/documents/expiring→ documents expiring within 30 days (dashboard).
 * GET  /api/documents/:id     → single document.
 * DELETE /api/documents/:id   → remove document (+ its storage artifact).
 */

const fs = require('fs');
const path = require('path');
const Document = require('../models/Document');
const aiService = require('../services/aiService');
const { uploadDir } = require('../middleware/multerConfig');

const EXPIRY_WINDOW_DAYS = 30;

/** Best-effort cleanup of the temporary upload artifact. */
function safeUnlink(filePath) {
  return fs.promises.unlink(filePath).catch((err) => {
    console.warn(`[gateway] Could not remove temp file ${filePath}: ${err.message}`);
  });
}

/**
 * POST /api/documents/upload
 * Requires: Bearer token + multipart field `file`.
 */
async function uploadDocument(req, res, next) {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded. Expected multipart field "file".' });
    }

    const file = req.file;

    // ── Phase 6 support: pull existing embeddings for semantic clustering ──
    let existingEmbeddings = [];
    try {
      existingEmbeddings = await Document.find({
        userId: req.userId,
        embedding: { $exists: true, $ne: [] },
      })
        .select('+embedding _id tags')
        .lean()
        .then((docs) =>
          docs.map((d) => ({ _id: String(d._id), embedding: d.embedding, tag: d.tags?.[0] || null }))
        )
        .catch(() => []); // clustering is best-effort; never block ingestion
    } catch {
      /* ignore — clustering degrades gracefully */
    }

    // ── Dispatch to the Python AI microservice (decoupled async HTTP) ──────
    let aiResult;
    try {
      aiResult = await aiService.processDocument(file, { existingEmbeddings });
    } catch (err) {
      await safeUnlink(file.path);
      return next(err); // errorHandler maps timeout / HTTP / network failures
    }

    // ── Map the AI response into the Document schema ───────────────────────
    const metadata = aiResult.metadata || {};
    const doc = await Document.create({
      userId: req.userId,
      originalFilename: file.originalname,
      storagePath: file.path, // container volume persists the artifact
      mimeType: file.mimetype,
      fileSize: file.size,
      extractedText: aiResult.extractedText || '',
      tags: Array.isArray(aiResult.tags) ? aiResult.tags : [],
      embedding: aiResult.embedding || undefined,
      metadata: {
        documentCategory: metadata.documentCategory || 'Others',
        idNumber: metadata.idNumber ?? null,
        name: metadata.name ?? null,
        issueDate: metadata.issueDate || null,
        expiryDate: metadata.expiryDate || null,
        autoGeneratedFilename: metadata.autoGeneratedFilename || file.originalname,
      },
    });

    const populated = await doc.populate('userId', 'username email');
    return res.status(201).json({ success: true, document: populated });
  } catch (err) {
    return next(err);
  }
}

/**
 * GET /api/documents?search=<query>&category=<cat>&limit=&skip=
 * Uses the MongoDB text index when `search` is present, otherwise a
 * userId + category compound-index scan.
 */
async function listDocuments(req, res, next) {
  try {
    const { search, category, limit = 50, skip = 0 } = req.query;
    const numericLimit = Math.min(Number(limit) || 50, 100);
    const numericSkip = Math.max(Number(skip) || 0, 0);

    let documents;
    if (search && String(search).trim()) {
      // Full-text search powered by the { extractedText, tags } text index.
      documents = await Document.textSearch(req.userId, String(search).trim(), {
        limit: numericLimit,
        skip: numericSkip,
      });
    } else {
      const filter = { userId: req.userId };
      if (category) filter['metadata.documentCategory'] = category;
      documents = await Document.find(filter)
        .sort({ createdAt: -1 })
        .skip(numericSkip)
        .limit(numericLimit)
        .lean();
    }

    return res.json({ success: true, count: documents.length, documents });
  } catch (err) {
    return next(err);
  }
}

/**
 * GET /api/documents/expiring
 * Documents whose `metadata.expiryDate` falls inside the next 30 days —
 * powers the Expiry Detection & Reminders dashboard widget.
 */
async function listExpiring(req, res, next) {
  try {
    const now = new Date();
    const horizon = new Date(now.getTime() + EXPIRY_WINDOW_DAYS * 24 * 60 * 60 * 1000);

    const documents = await Document.find({
      userId: req.userId,
      'metadata.expiryDate': { $gte: now, $lte: horizon },
    })
      .sort({ 'metadata.expiryDate': 1 })
      .lean();

    return res.json({
      success: true,
      windowDays: EXPIRY_WINDOW_DAYS,
      count: documents.length,
      documents,
    });
  } catch (err) {
    return next(err);
  }
}

/** GET /api/documents/:id */
async function getDocument(req, res, next) {
  try {
    const doc = await Document.findOne({ _id: req.params.id, userId: req.userId }).lean();
    if (!doc) {
      return res.status(404).json({ error: 'Document not found' });
    }
    return res.json({ success: true, document: doc });
  } catch (err) {
    return next(err);
  }
}

/** DELETE /api/documents/:id — removes the DB record and its stored artifact. */
async function deleteDocument(req, res, next) {
  try {
    const doc = await Document.findOneAndDelete({ _id: req.params.id, userId: req.userId });
    if (!doc) {
      return res.status(404).json({ error: 'Document not found' });
    }

    // Artifact may live outside uploadDir (object storage) — attempt only
    // when the resolved path stays inside the configured cache directory.
    const resolved = path.resolve(doc.storagePath);
    if (resolved.startsWith(path.resolve(uploadDir))) {
      await safeUnlink(resolved);
    }

    return res.json({ success: true, deletedId: doc._id });
  } catch (err) {
    return next(err);
  }
}

module.exports = {
  uploadDocument,
  listDocuments,
  listExpiring,
  getDocument,
  deleteDocument,
  EXPIRY_WINDOW_DAYS,
};
