"""
main.py — FastAPI AI microservice (Phases 3–6)

Single endpoint ``POST /process-document`` implements the full intelligence
pipeline:

    upload → decode → blur safeguard → CV preprocessing (2× upscale,
             Gaussian blur, adaptive binarization) → Tesseract LSTM OCR
             (eng+hin) → NLP sanitization → entity extraction (PAN/Aadhaar/
             dates/names) → semantic embedding → cluster join → standardized
             filename → structured JSON response for the Node.js gateway.

PDF uploads first try direct text extraction using PyMuPDF. If no selectable
text is found, the PDF is rasterized page-by-page (pdf2image) and processed
through the existing OCR pipeline.
"""

from __future__ import annotations

import json
import logging
from typing import List, Optional

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from . import extractor, ocr, preprocessing, semantic


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)

logger = logging.getLogger("ai-service")


ALLOWED_MIME_TYPES = {
    "image/jpeg",
    "image/png",
    "application/pdf",
}


# Category mapping produced by the classifier (Phase 5 → schema enum).
CATEGORY_BY_TYPE = {
    # ID Proof
    "Aadhaar": "ID Proof",
    "Driving Licence": "ID Proof",
    "Passport": "ID Proof",
    "Voter ID": "ID Proof",

    # Education
    "Marksheet": "Education",
    "Study Plan": "Education",
    "Study Strategy": "Education",
    "Study Material": "Education",
    "Assignment": "Education",

    # Finance
    "PAN": "Finance",
    "Bank Statement": "Finance",
    "Salary Slip": "Finance",
    "Invoice": "Finance",

    # Insurance
    "Insurance": "Insurance",
}


app = FastAPI(
    title="AI Document Intelligence Service",
    description=(
        "OpenCV preprocessing, Tesseract OCR, entity extraction and "
        "semantic clustering for the Intelligent Document Organizer."
    ),
    version="1.0.0",
)


# The Node.js gateway calls server-side; permissive CORS only aids debugging.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health() -> dict:
    return {
        "status": "ok",
        "service": "doc-organizer-ai",
    }


def _category_for(doc_type: str) -> str:
    """Map classifier output to the Document schema category enum."""
    return CATEGORY_BY_TYPE.get(doc_type, "Others")


def _build_metadata(
    doc_type: str,
    entities: dict,
    extension: str,
) -> dict:
    """Assemble the metadata object consumed by the Node.js Document schema."""
    return {
        "documentCategory": _category_for(doc_type),
        "idNumber": entities.get("ID_Number"),
        "name": entities.get("Name"),
        "issueDate": entities.get("Issue_Date"),
        "expiryDate": entities.get("Expiry_Date"),
        "autoGeneratedFilename": semantic.generate_filename(
            {
                **entities,
                "extension": extension,
            }
        ),
    }


@app.post("/process-document")
async def process_document(
    file: UploadFile = File(...),
    existing_embeddings: str = Form("[]"),
) -> JSONResponse:
    """
    Process a single uploaded document (image or PDF) end-to-end.

    Args:
        file: Multipart upload — image/jpeg, image/png or application/pdf.
        existing_embeddings: Optional JSON array of prior document records
            ``[{'_id', 'embedding', 'tag'}]`` for semantic cluster joining.

    Returns:
        Structured JSON:
        ``{ originalFilename, mimeType, fileSize, extractedText,
        cleanedTextArray, documentType, metadata, tags, embedding,
        clusterTag, similarityScore }``

    Raises:
        HTTPException 400: unreadable buffer / excessively blurry document.
        HTTPException 415: unsupported MIME type.
    """

    # ── 0. Validation ──────────────────────────────────────────────────────
    if file.content_type not in ALLOWED_MIME_TYPES:
        raise HTTPException(
            status_code=415,
            detail=(
                f"Unsupported media type '{file.content_type}'. "
                f"Allowed: {sorted(ALLOWED_MIME_TYPES)}"
            ),
        )

    file_bytes = await file.read()

    if not file_bytes:
        raise HTTPException(
            status_code=400,
            detail="Uploaded file is empty",
        )

    is_pdf = file.content_type == "application/pdf"

    # ── 1. Decode + blur safeguard + CV preprocessing + OCR ────────────────
    try:
        if is_pdf:
            # First try direct text extraction from the PDF.
            #
            # This is useful for normal/selectable-text PDFs because
            # rasterizing them and sending them through OCR is unnecessary.
            raw_text = preprocessing.extract_text_from_pdf(file_bytes)

            if raw_text.strip():
                logger.info(
                    "Selectable text found in PDF %s; "
                    "using direct PDF text extraction.",
                    file.filename,
                )
            else:
                # No selectable text was found.
                # This is most likely a scanned/image-based PDF, so use
                # the existing PDF → image → preprocessing → OCR pipeline.
                logger.info(
                    "No selectable text found in PDF %s; "
                    "falling back to PDF OCR.",
                    file.filename,
                )

                pages = preprocessing.pdf_bytes_to_matrices(file_bytes)

                # Apply the pipeline (incl. blur detection) iteratively per page.
                sharp_pages: List = []

                for page in pages:
                    try:
                        preprocessing.assert_sharp(page)

                        sharp_pages.append(
                            preprocessing.preprocess_image(page)
                        )

                    except preprocessing.BlurryDocumentError as exc:
                        logger.warning(
                            "Skipping blurry PDF page: %s",
                            exc,
                        )

                if not sharp_pages:
                    raise HTTPException(
                        status_code=400,
                        detail=(
                            "PDF pages are too blurry for processing "
                            f"(Laplacian variance < "
                            f"{preprocessing.BLUR_THRESHOLD:.1f})"
                        ),
                    )

                raw_text = await ocr.extract_text_from_pages(
                    sharp_pages
                )

        else:
            # Normal image upload.
            image = preprocessing.bytes_to_image(file_bytes)

            variance = preprocessing.assert_sharp(image)

            logger.info(
                "Laplacian variance for %s: %.2f",
                file.filename,
                variance,
            )

            binary = preprocessing.preprocess_image(image)

            raw_text = await ocr.extract_text(binary)

    except preprocessing.InvalidImageError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    except preprocessing.BlurryDocumentError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    # ── 2. NLP sanitization + entity extraction (Phase 5) ──────────────────
    entities = extractor.extract_entities(raw_text)

    doc_type = entities["Document_Type"]

    cleaned_lines = entities["Cleaned_Text_Array"]

    # ── 3. Semantic embedding + cluster join (Phase 6) ─────────────────────
    embedding: Optional[List[float]] = None

    try:
        embedding = semantic.generate_embedding(
            " ".join(cleaned_lines)
        )

    except Exception as exc:  # noqa: BLE001 — clustering must never 500 the upload
        logger.warning(
            "Embedding generation failed: %s",
            exc,
        )

    cluster_tag: Optional[str] = None
    similarity_score = 0.0

    if embedding:
        try:
            existing = json.loads(
                existing_embeddings or "[]"
            )

        except json.JSONDecodeError:
            existing = []

        cluster_tag, similarity_score = semantic.cluster_tag(
            embedding,
            existing,
        )

    # Default tag: cluster label if joined, else a type-derived label.
    tags = (
        [cluster_tag]
        if cluster_tag
        else [
            doc_type
            if doc_type != "Unknown"
            else "Miscellaneous"
        ]
    )

    # ── 4. Structured response for the Node.js orchestrator ────────────────
    extension = (
        (file.filename or "").rsplit(".", 1)[-1]
        if file.filename
        else "jpg"
    )

    return JSONResponse(
        content={
            "originalFilename": file.filename,
            "mimeType": file.content_type,
            "fileSize": len(file_bytes),
            "extractedText": raw_text,
            "cleanedTextArray": cleaned_lines,
            "documentType": doc_type,
            "metadata": _build_metadata(
                doc_type,
                entities,
                extension,
            ),
            "tags": tags,
            "embedding": embedding,
            "clusterTag": cluster_tag,
            "similarityScore": round(
                similarity_score,
                4,
            ),
        }
    )