/**
 * mock-api.mjs — DEMO-ONLY stub of the Node.js gateway (NOT part of the
 * production stack; docker-compose runs the real backend).
 *
 * Lets you exercise the Phase 7 React dashboard end-to-end without MongoDB
 * or the Python AI service: in-memory documents, fake JWT issuance, and a
 * simulated AI-processing delay on upload.
 *
 * Usage:  node tools/mock-api.mjs   (listens on 0.0.0.0:5000)
 */

import http from 'node:http';
import crypto from 'node:crypto';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const PORT = Number(process.env.MOCK_API_PORT || 5000);
const AI_DELAY_MS = 2500;

/* ── Tiny dependency-free JWT (demo only) ─────────────────────────────── */
const SECRET = 'mock_secret_demo_only';
const b64 = (obj) => Buffer.from(JSON.stringify(obj)).toString('base64url');
function signToken(userId) {
  const header = b64({ alg: 'HS256', typ: 'JWT' });
  const payload = b64({ sub: String(userId), iat: Date.now() / 1000, exp: Date.now() / 1000 + 604800 });
  const sig = crypto.createHmac('sha256', SECRET).update(`${header}.${payload}`).digest('base64url');
  return `${header}.${payload}.${sig}`;
}

/* ── In-memory store ──────────────────────────────────────────────────── */
const users = [];
const docs = [];
let idSeq = 1;

const daysFromNow = (n) => new Date(Date.now() + n * 86400000).toISOString();
const iso = (y, m, d) => new Date(y, m - 1, d).toISOString();

function seed() {
  users.push({ _id: 'u1', username: 'demo', email: 'demo@example.com', preferences: { theme: 'light' } });
  const samples = [
    {
      originalFilename: 'IMG_9912.jpg', mimeType: 'image/jpeg', category: 'ID Proof',
      autoGeneratedFilename: 'Aadhaar_Card_Priya_Patel_2026-08-17.jpg', idNumber: '2345 6789 0123',
      name: 'Priya Patel', expiryDate: null, issueDate: iso(2018, 4, 12),
      extractedText: 'UIDAI Government of India Priya Patel DOB 22/11/1992',
      tags: ['Aadhaar'],
    },
    {
      originalFilename: 'scan_pan.pdf', mimeType: 'application/pdf', category: 'Finance',
      autoGeneratedFilename: 'PAN_Card_Vikram_Singh_2026-08-17.jpg', idNumber: 'ABCDE1234F',
      name: 'Vikram Singh', expiryDate: null, issueDate: iso(2019, 3, 5),
      extractedText: 'Income Tax Department Permanent Account Number ABCDE1234F',
      tags: ['PAN'],
    },
    {
      originalFilename: 'insurance_policy.pdf', mimeType: 'application/pdf', category: 'Insurance',
      autoGeneratedFilename: 'Insurance_Policy_Meera_Joshi_2026-08-17.pdf', idNumber: 'POL-889120',
      name: 'Meera Joshi', expiryDate: daysFromNow(12), issueDate: iso(2024, 9, 1),
      extractedText: 'Term insurance policy valid till 29/08/2026 premium renewal',
      tags: ['finance', 'renewal'],
    },
    {
      originalFilename: 'passport_scan.png', mimeType: 'image/png', category: 'ID Proof',
      autoGeneratedFilename: 'Passport_Arjun_Nair_2026-08-17.png', idNumber: 'N1234567',
      name: 'Arjun Nair', expiryDate: daysFromNow(120), issueDate: iso(2021, 6, 20),
      extractedText: 'Passport Republic of India Arjun Nair valid until 15/12/2031',
      tags: ['Passport'],
    },
    {
      originalFilename: 'degree_certificate.pdf', mimeType: 'application/pdf', category: 'Education',
      autoGeneratedFilename: 'Degree_Certificate_Sneha_Iyer_2026-08-17.pdf', idNumber: 'B.TECH-2019-445',
      name: 'Sneha Iyer', expiryDate: null, issueDate: iso(2019, 7, 15),
      extractedText: 'Bachelor of Technology degree certificate issued by university',
      tags: ['Education'],
    },
    {
      originalFilename: 'driving_licence.jpg', mimeType: 'image/jpeg', category: 'ID Proof',
      autoGeneratedFilename: 'Driving_Licence_Rahul_Mehta_2026-08-17.jpg', idNumber: 'DL-042019-887123',
      name: 'Rahul Mehta', expiryDate: daysFromNow(6), issueDate: iso(2022, 1, 10),
      extractedText: 'Driving licence valid upto 23/08/2026 transport authority',
      tags: ['Licence'],
    },
    {
      originalFilename: 'health_insurance.png', mimeType: 'image/png', category: 'Insurance',
      autoGeneratedFilename: 'Health_Insurance_Family_2026-08-17.png', idNumber: 'HI-77891234',
      name: 'Family Floater', expiryDate: daysFromNow(45), issueDate: iso(2025, 12, 1),
      extractedText: 'Health insurance family floater policy valid till 01/10/2026',
      tags: ['health'],
    },
  ];
  for (const s of samples) {
    docs.push({
      _id: `d${idSeq++}`, userId: 'u1', fileSize: 420000 + idSeq * 1024,
      storagePath: '/demo/uploads', createdAt: new Date(Date.now() - idSeq * 86400000).toISOString(),
      updatedAt: new Date().toISOString(), extractedText: s.extractedText, tags: s.tags, embedding: [],
      originalFilename: s.originalFilename, mimeType: s.mimeType,
      metadata: {
        documentCategory: s.category, idNumber: s.idNumber, name: s.name,
        issueDate: s.issueDate, expiryDate: s.expiryDate, autoGeneratedFilename: s.autoGeneratedFilename,
      },
    });
  }
}

/* ── Helpers ──────────────────────────────────────────────────────────── */
const json = (res, code, body) => {
  res.writeHead(code, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
  res.end(JSON.stringify(body));
};
const readBody = (req) =>
  new Promise((resolve) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
  });

/* Multipart parse — only used for the `file` field metadata (demo). */
function parseMultipartName(raw) {
  const m = raw.match(/name="file"; filename="([^"]+)"/);
  return m ? m[1] : 'upload.jpg';
}

/* Simulate the AI pipeline result for an arbitrary upload. */
function simulateAiResult(filename) {
  const ext = (filename.split('.').pop() || 'jpg').toLowerCase();
  const mime = ext === 'pdf' ? 'application/pdf' : ext === 'png' ? 'image/png' : 'image/jpeg';
  const pool = [
    { category: 'ID Proof', label: 'Aadhaar', id: `${Math.floor(1000 + Math.random() * 9000)} ${Math.floor(1000 + Math.random() * 9000)} ${Math.floor(1000 + Math.random() * 9000)}`, name: 'Demo User', text: 'UIDAI Government of India Demo User' },
    { category: 'Finance', label: 'PAN', id: 'C' + 'K'.repeat(4) + Math.floor(1000 + Math.random() * 9000) + 'F', name: 'Demo User', text: 'Income Tax Department Permanent Account Number' },
    { category: 'Insurance', label: 'Insurance', id: `POL-${Math.floor(100000 + Math.random() * 900000)}`, name: 'Demo User', text: 'Policy document valid till 30/09/2026' },
  ];
  const pick = pool[Math.floor(Math.random() * pool.length)];
  const base = pick.label.replace(/\s+/g, '_');
  return {
    extractedText: pick.text,
    documentType: pick.label,
    tags: [pick.label],
    metadata: {
      documentCategory: pick.category,
      idNumber: pick.id,
      name: pick.name,
      issueDate: iso(2024, 5, 1),
      expiryDate: pick.category === 'Insurance' ? daysFromNow(25) : null,
      autoGeneratedFilename: `${base}_${pick.name.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.${ext}`,
    },
  };
}

/* ── Router ───────────────────────────────────────────────────────────── */
const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const { pathname } = url;
  const method = req.method;

  if (method === 'OPTIONS') {
    res.writeHead(204, { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Allow-Headers': '*' });
    return res.end();
  }

  try {
    // ── Auth ──
    if (pathname === '/api/auth/register' && method === 'POST') {
      const { username, email } = JSON.parse(await readBody(req));
      const user = { _id: `u${++idSeq}`, username, email, preferences: { theme: 'light' } };
      users.push(user);
      return json(res, 201, { success: true, token: signToken(user._id), user });
    }
    if (pathname === '/api/auth/login' && method === 'POST') {
      const { email } = JSON.parse(await readBody(req));
      const user = users.find((u) => u.email === email) || users[0];
      return json(res, 200, { success: true, token: signToken(user._id), user });
    }
    if (pathname === '/api/auth/me' && method === 'GET') {
      return json(res, 200, { success: true, user: users[0] });
    }

    // ── Documents ──
    if (pathname === '/api/documents' && method === 'GET') {
      const search = (url.searchParams.get('search') || '').toLowerCase();
      const category = url.searchParams.get('category');
      let list = [...docs];
      if (category) list = list.filter((d) => d.metadata.documentCategory === category);
      if (search) {
        list = list.filter((d) =>
          [d.extractedText, d.tags.join(' '), d.metadata.idNumber, d.metadata.name, d.metadata.documentCategory, d.metadata.autoGeneratedFilename]
            .join(' ')
            .toLowerCase()
            .includes(search)
        );
      }
      return json(res, 200, { success: true, count: list.length, documents: list });
    }
    if (pathname === '/api/documents/expiring' && method === 'GET') {
      const now = Date.now();
      const list = docs.filter((d) => {
        const exp = d.metadata.expiryDate ? new Date(d.metadata.expiryDate).getTime() : null;
        return exp && exp >= now && exp <= now + 30 * 86400000;
      });
      return json(res, 200, { success: true, windowDays: 30, count: list.length, documents: list });
    }
    if (pathname === '/api/documents/upload' && method === 'POST') {
      const raw = await readBody(req);
      const filename = parseMultipartName(raw);
      // Simulate the Python AI microservice latency.
      await new Promise((r) => setTimeout(r, AI_DELAY_MS));
      const ai = simulateAiResult(filename);
      const doc = {
        _id: `d${++idSeq}`, userId: 'u1', originalFilename: filename,
        storagePath: `/tmp/mock-uploads/${crypto.randomUUID()}`, mimeType: ai.mimeType || 'image/jpeg',
        fileSize: raw.length, extractedText: ai.extractedText, tags: ai.tags, embedding: [],
        metadata: ai.metadata,
        createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
      };
      docs.unshift(doc);
      return json(res, 201, { success: true, document: doc });
    }
    const delMatch = pathname.match(/^\/api\/documents\/(d\d+)$/);
    if (delMatch && method === 'DELETE') {
      const idx = docs.findIndex((d) => d._id === delMatch[1]);
      if (idx === -1) return json(res, 404, { error: 'Document not found' });
      const [removed] = docs.splice(idx, 1);
      return json(res, 200, { success: true, deletedId: removed._id });
    }

    return json(res, 404, { error: 'Route not found' });
  } catch (err) {
    return json(res, 500, { error: err.message });
  }
});

seed();
server.listen(PORT, '0.0.0.0', () => {
  console.log(`[mock-api] DEMO gateway listening on http://0.0.0.0:${PORT}`);
  console.log('[mock-api] Seeded', docs.length, 'documents — login with demo@example.com (any password)');
});
